requires:
- category: "development"
  name: "toolchain"
  version: ">=0"
- name: libnftnl
  category: libs
  version: ">=0"
- name: "libmnl"
  category: "libs"
  version: ">=0"

env:
- CFLAGS="-D_GNU_SOURCE -I/include -I/usr/include -static -fPIC"
- LDFLAGS="-L/usr/lib -L/lib"

package_dir: /{{.Values.name}}
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   luet install utils/autoconf development/make development/automake vcs/git development/m4 libs/libressl && \
   mkdir -p /${PACKAGE_NAME} && mkdir ${PACKAGE_NAME} && \
   wget https://www.netfilter.org/projects/iptables/files/iptables-${PACKAGE_VERSION}.tar.bz2 -O iptables.tar.bz2 && tar -xvf iptables.tar.bz2 -C ./ && mv iptables-$PACKAGE_VERSION ${PACKAGE_NAME}
steps:
- cd ${PACKAGE_NAME}/${PACKAGE_NAME}-$PACKAGE_VERSION && ./configure --prefix=/usr --without-kernel --enable-devel --enable-libipq --enable-shared --sbindir=/sbin
- cd ${PACKAGE_NAME}/${PACKAGE_NAME}-$PACKAGE_VERSION && make -j8
- cd ${PACKAGE_NAME}/${PACKAGE_NAME}-$PACKAGE_VERSION && make DESTDIR=/${PACKAGE_NAME} install
- cd ${PACKAGE_NAME}/${PACKAGE_NAME}-$PACKAGE_VERSION && cp -rfv include "/${PACKAGE_NAME}"/usr
